### PR TITLE
Make the user pass in a WebRTC implementation (for #7)

### PR DESCRIPTION
**Pull request by paulkernfeld**
Hopefully this change isn't too invasive. This seemed like the most straightforward way to do it.

Also a quick note that this is a breaking change.

### CODE REVIEW

**Comment by mappum** [comment]
Hey @paulkernfeld, thanks for contributing! Although I should let you know that a lot of the code inside this repo is already being moved into smaller repos, see the roadmap in the README for links.

**Comment by paulkernfeld** [comment]
Ah, okay, now I see that this is approach is already implemented in peerGroup in bitcoin-net for example, so that will make this PR obsolete soon. Do you have an ETA for finishing the refactor?

**Comment by mappum** [comment]
>Do you have an ETA for finishing the refactor?

I'm looking to get it done ASAP, but I'm bad at time estimates. Maybe 3 or 4 days of work. #13

**Comment by paulkernfeld** [comment]
Nice! That's super fast, so it's probably not worth it to merge this PR.

**Comment by mappum** [comment]
Closing because this feature is in `bitcoin-net`.

**Comment by paulkernfeld** [comment]
Awesome!

**Pull request closed without merging**
