### PR TITLE
Add the debug package, and debug statements in lib/bridge.js

### PR DESCRIPTION
**Pull request by paulkernfeld**
This helped me in tracking down issue #5. Do you think this is a good direction? If so, I'm happy to add more debug statements.

### CODE REVIEW

**Comment by mappum** [comment]
Thanks for this. If you change the scope from `webcoin` to `webcoin:bridge` I'll merge this. I do think debug statements are good, but there is definitely such a thing as too many. We'll have to mess around with it and find a good balance that gives us meaningful logs without too much noise.

**Comment by mappum** [comment]
BTW, I plan on breaking the bridge code out into its own repo (named `bitcoin-web-bridge`).

**Comment by paulkernfeld** [comment]
Yup, I agree with avoiding too much clutter. Just let me know if this is too noisy.

**Comment by mappum** [comment]
This is probably OK since the bridge code is mostly run on its own.

**Pull request merged**
